version: '3.9'

services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d

  api:
    depends_on: 
      - db
    build:
      context: ./api
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_HOST: db
      MYSQL_DATABASE: app
  
  front:
    depends_on: 
      - api
    build:
      context: ./front
    restart: always
    environment:
      API_HOST_ADDR: "http://api"
    ports:
      - "8080:80"
