CREATE TABLE IF NOT EXISTS `posts` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`title` TINYTEXT NOT NULL,
	`content` TEXT NOT NULL,
	`create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `comments` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`poster` TINYTEXT NOT NULL,
	`content` TEXT NOT NULL,
	`create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`post_id` BIGINT NOT NULL,
	PRIMARY KEY (`id`),
	FOREIGN KEY (`post_id`) REFERENCES `posts`(`id`)
);